name: create-release-binaries

on:
  release:
    types:
      - created

env:
  BUILD_TYPE: Release
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ARCHIVE_NAME: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}
    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build with CMake
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Create Archive
      run: tar -czf "$ARCHIVE_NAME".tar.gz ${{github.workspace}}/build/Recrypt/Recrypt
    - name: Upload to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload ${{ github.event.release.tag_name }} $ARCHIVE_NAME
