name: create-reelease-binaries

on:
  release:
    types:
      - created

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build with CMake
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Upload to release
      run: |
        for f in $(find . -name '${{github.workspace}}/build/Recrypt/Release/*'); do
          gh release upload ${{ github.event.release.tag_name }} $f
        done
